name: Build VSCode Tests for Playwright

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  FORCE_COLOR: 1

jobs:
  build:
    runs-on: ${{ matrix.os }}
    name: Run tests on ${{ matrix.os }}, Node ${{ matrix.node-version }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
        node-version: [ 20 ]
        include:
        - os: ubuntu-latest
          node-version: 18
    timeout-minutes: 60
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build
    - run: xvfb-run npx playwright test
      if: matrix.os == 'ubuntu-latest'
    - run: npx playwright test
      if: matrix.os != 'ubuntu-latest'
    - run: npm pack
      if: matrix.os == 'ubuntu-latest' && matrix.node-version == '20'
    - uses: actions/upload-artifact@v4
      if: matrix.os == 'ubuntu-latest' && matrix.node-version == '20'
      with:
        name: npm-package
        path: "vscode-test-playwright-*.tgz"
        retention-days: 30
